[build]
  publish = "_site"
  command = "jekyll build"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/plots/*"
    [headers.values]
    Content-Type = "text/html"
